version: 2

builds:
  - binary: env-pilot
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "env-pilot_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: tomenden
    name: env-pilot
